### ISSUE TITLE
update to scala 2.11

### ISSUE THREAD

**Issue by eodgooch** [foursquare/foursquare-fhttp#13]
Finagle has been compiled scala 2.11 for some time now and I'd like to use your client in some of my projects. Unfortunately I am forced to compile my own build for scala 2.11. There is a PR for scala 2.11, please merge it.

**Comment by mattweyant** [comment]
+1

**Comment by mateor** [comment]
Hi - sorry for the delayed response. We are going to be deprecating this library sometime before the summer. We have a new home for this project - https://github.com/foursquare/fsqio. This is a repo that holds all of our OSS projects in one place. Our hope is that this will be a benefit to any open source consumers - this is split out directly from our internal monorepo so we will be pushing all fixes to users the same way we use them.

We have already published jars to maven: https://maven-repository.com/artifact/io.fsq so they can be consumed as of now. 

As for this particular issue - one drawback to this approach is that it is not easy to publish jars with dependencies that aren't a part of our current stack. Upgrading a single project to Scala 2.11 would be non-trivial. But we are actively upgrading our repo to 2.11 as we speak. There is no ETA, but once we complete that upgrade, I will republish 2.11 jars from fsq.io and close this issue for you.

**Comment by mateor** [comment]
It was a longer process than we would have liked, but these jars have been published for Scala 2.11. As stated above, we have moved to Scala 2.11 internally, so this marks the end of support for Scala 2.10.

As a reminder, this repo is deprecated. The code is up at the new home for this project, [Fsq.io](https://github.com/foursquare/fsqio/tree/master/src/jvm/io/fsq/fhttp), and the jars are up [on Maven](https://repo1.maven.org/maven2/io/fsq/).
